apiVersion: compute.cloud.com/v1
kind: EC2Instance
metadata:
  name: web-server-1
  namespace: default
spec:
  instanceType: t3.micro
  amiId: ami-0230bd60aa48260c6
  region: us-east-1
  availabilityZone: us-east-1a
  keyPair: my-key-pair
  securityGroups:
    - sg-0123456789abcdef0
  subnet: subnet-0a1b2c3d4e5f67890
  associatePublicIP: true
  storage:
    rootVolume:
      size: 20
      type: gp3
      encrypted: false
    additionalVolumes:
      - size: 50
        type: gp3
        deviceName: /dev/sdf
        encrypted: false
  tags:
    Environment: production
    Owner: platform-team
    Name: k8s-managed-web-server
  userData: |
    #!/bin/bash
    echo "Hello World" > /tmp/hello.txt