apiVersion: compute.cloud.com/v1
kind: EC2Instance
metadata:
  name: web-server-2
  namespace: default
spec:
  instanceType: t3.micro
  amiId: ami-0230bd60aa48260c6
  region: us-east-1
  availabilityZone: us-east-1a
  keyPair: ${K8S_KEY_PAIR}
  securityGroups:
    - ${K8S_SECURITY_GROUP}
  subnet: ${SUBNET_ID}
  associatePublicIP: true
  storage:
    rootVolume:
      size: 20
      type: gp3
      encrypted: false
    additionalVolumes:
      - size: 50
        type: gp3
        deviceName: /dev/sdf
        encrypted: false
  tags:
    Environment: production
    Owner: platform-team
    Name: k8s-managed-web-server
  userData: |
    #!/bin/bash
    echo "Hello World" > /tmp/hello.txt